### ISSUE TITLE
ImportError: No module named angle_of_line

### ISSUE THREAD

**Issue by MHZarei** [TargaryenGitHub/mscThesis_HaoxiangWu#2]
Hi
I wanna run main.py, but show this error:

`$ python main.py 
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from fix_drafting_errors import fix_duplicated_lines
  File "mscThesis_HaoxiangWu/fix_drafting_errors.py", line 3, in <module>
    from angle_of_line import angle_of_line
ImportError: No module named angle_of_line
`

Could you help me to fix this? 
Thanks for your attention

**Comment by SrishtiSustainabilityStudio** [comment]
I too tried running the main program but got the same error.
Not sure what is the problem.

Thanks, 
Srishti.

**Comment by SrishtiSustainabilityStudio** [comment]
Also, why are three files taken as input. The shape files not there in the download folder.

Thanks,
Srishti.
